### ISSUE TITLE
Installationsanleitung nicht mehr zu knitten

### ISSUE THREAD

**Issue by Bia-Ka** [luebby/Datenanalyse-mit-R#13]
Hallo in die Runde,

nachdem die Vorlesungen jetzt wieder laufen (Danke, @NMarkgraf !), hapert es jetzt an der Installationsanleitung. Folgender Fehler kommt:

` "C:/PROGRA~1/Pandoc/pandoc" +RTS -K512m -RTS Install.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output Install.tex --self-contained --highlight-style tango --pdf-engine pdflatex --include-in-header preamble.tex --lua-filter "C:/ProgrammeBK/Statistik/R/R-3.6.2/library/rmarkdown/rmd/lua/pagebreak.lua" --lua-filter "C:/ProgrammeBK/Statistik/R/R-3.6.2/library/rmarkdown/rmd/lua/latex-div.lua" --standalone -V graphics=TRUE 
! Undefined control sequence.
l.126 \setstretch
                 {1.44} `

`Error: LaTeX failed to compile Install.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See Install.log for more info.`

[Install.log](https://github.com/luebby/Datenanalyse-mit-R/files/4182007/Install.log)

@TabeaT , könntest du mir bitte morgen die aktuelle Installationsanleitung als PDF erstellen und zuschicken? Danke schön.

Viele Grüße
Bianca

**Comment by NMarkgraf** [comment]
Dear Bianca,

pull it, and try it again!

Works for me.

Best regards,
Norman

**Comment by Bia-Ka** [comment]
Dear Norman,

thanks a lot - it works for me, too! :-)

Best regards
Bianca

@TabeaT : Dann benötige ich keine PDF mehr.
