### ISSUE TITLE
Paket hexbin

### ISSUE THREAD

**Issue by Bia-Ka** [luebby/Datenanalyse-mit-R#5]
Der Anhang "Datenjudo" wurde bei mir (Rechner neu aufgesetzt) nicht richtig erzeugt, weil das Paket hexbin vorher installiert und geladen sein muss. Das scheint aber nicht in der Prüfroutine zu sein. Das sollten wir mit aufnehmen.

**Comment by luebby** [comment]
Danke. Da die Übungshefte ja nicht individuell sind haben wir hier keine Abfrageroutine. Aber @MGehrke wollte sich der Übungshefte dieses Semester mal annehmen...

**Comment by Bia-Ka** [comment]
Stimmt ja, die werden nicht individuell erzeugt, daher dann nicht so wichtig...
