### ISSUE TITLE
Fehlermeldung Übungshefte

### ISSUE THREAD

**Issue by Bia-Ka** [luebby/Datenanalyse-mit-R#6]
Hallo zusammen,
ich erhalte beim knittr gerade die Meldung "Syntax Error (3951): Unknown filter 'DCTDecode' " Das PDF wird erzeugt und ich habe auch noch  nicht gefunden, worauf sich die Fehlermeldung auswirkt. Augenscheinlich sieht alles ganz okay aus...
Hat jemand eine Idee?
Viele Grüße
Bianca

**Comment by luebby** [comment]
Erste Recherschen ergeben, dass das ein MikeTex Problem gewesen sein könnte. Evt. mal Latex Pakete aktualisieren? [https://sourceforge.net/p/miktex/bugs/2605/](https://sourceforge.net/p/miktex/bugs/2605/)

**Comment by Bia-Ka** [comment]
Oh, ich probiere...

**Comment by Bia-Ka** [comment]
... und das war es - hat geklappt. Danke für den Tipp!
